"use client";

import { useActionState, useState } from "react";
import type { ActionResult } from "@/lib/vendor-management/actions";
import type { DiscoveryOptions } from "@/lib/vendors/discovery-params";

type Action = (state: ActionResult, form: FormData) => Promise<ActionResult>;
const input = "mt-2 min-h-12 w-full rounded-xl border border-hutan/25 bg-white px-3 py-2 text-base";
export function ActionForm({ action, children, label }: { action: Action; children: React.ReactNode; label: string }) {
  const [state, submit, pending] = useActionState(action, { message: "" });
  return <form action={submit} className="space-y-5" aria-busy={pending}><fieldset disabled={pending} className="min-w-0 space-y-5">{children}</fieldset>{state.message && <p role={state.ok ? "status" : "alert"} className="rounded-xl bg-rembulan/40 p-4 text-sm">{state.message}</p>}<button type="submit" disabled={pending} className="min-h-12 rounded-xl bg-hutan px-6 py-3 font-semibold text-white disabled:opacity-60">{pending ? "Please wait…" : label}</button></form>;
}
export function AuthForm({ action, registration }: { action: Action; registration: boolean }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  return <ActionForm action={action} label={registration ? "Create vendor account" : "Sign in"}><label className="block">Email<input required type="email" name="email" value={email} onChange={(event) => setEmail(event.target.value)} maxLength={254} autoComplete="email" className={input} /></label><label className="block">Password<input required type="password" name="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={registration ? 12 : undefined} maxLength={128} autoComplete={registration ? "new-password" : "current-password"} className={input} /></label>{registration && <p className="text-sm text-[#5d665f]">Use at least 12 characters. We’ll email you to confirm your account.</p>}</ActionForm>;
}
export function ProfileForm({ options, initial = {}, action, onboarding = false }: { options: DiscoveryOptions; initial?: Record<string, string | null>; action: Action; onboarding?: boolean }) {
  const [values, setValues] = useState(initial);
  const change = (name: string, value: string, reset: string[] = []) => setValues((old) => ({ ...old, ...Object.fromEntries(reset.map((key) => [key, ""])), [name]: value }));
  const text = (name: string, label: string, max: number, required = false) => <label className="block" key={name}>{label}<input name={name} value={values[name] || ""} onChange={(event) => change(name, event.target.value)} maxLength={max} required={required} className={input} /></label>;
  const select = (name: string, label: string, choices: { id: string; name: string }[], required: boolean, reset: string[] = []) => <div><label htmlFor={name} className="block">{label}</label><select id={name} name={name} value={values[name] || ""} onChange={(event) => change(name, event.target.value, reset)} required={required} className={input}><option value="">{required ? "Choose…" : "None / not listed"}</option>{choices.map((choice) => <option key={choice.id} value={choice.id}>{choice.name}</option>)}</select></div>;
  return <ActionForm action={action} label={onboarding ? "Create business & continue" : "Save profile"}>
    <section className="space-y-5"><h2 className="font-serif text-2xl">1. Your business</h2>{text("name", "Business name", 160, true)}<label className="block">Description (optional)<textarea name="description" value={values.description || ""} onChange={(event) => change("description", event.target.value)} maxLength={5000} rows={4} className={input} /></label><div className="grid gap-5 sm:grid-cols-2">{select("category_id", "Category", options.categories, true, ["subcategory_id"])}{select("subcategory_id", "Subcategory (optional)", options.subcategories.filter((item) => item.category_id === values.category_id), false)}</div></section>
    <section className="space-y-5 border-t border-hutan/10 pt-6"><h2 className="font-serif text-2xl">2. Location</h2><div className="grid gap-5 sm:grid-cols-2">{select("state_id", "State", options.states, true, ["city_id", "area_id"])}{select("city_id", "City / district", options.cities.filter((item) => item.state_id === values.state_id), true, ["area_id"])}</div>{select("area_id", "Area / locality (optional)", options.areas.filter((item) => item.city_id === values.city_id), false)}{text("address", "Street address (optional)", 1000)}</section>
    <section className="space-y-5 border-t border-hutan/10 pt-6"><h2 className="font-serif text-2xl">3. Contact (optional)</h2><p className="text-sm text-[#5d665f]">These details will be public after approval.</p><div className="grid gap-5 sm:grid-cols-2">{text("phone", "Phone", 32)}{text("whatsapp", "WhatsApp", 32)}{text("website_url", "Website URL", 2048)}{text("instagram_url", "Instagram URL", 2048)}{text("tiktok_url", "TikTok URL", 2048)}{text("facebook_url", "Facebook URL", 2048)}</div></section>
    {onboarding && <p className="rounded-xl bg-rembulan/30 p-4 text-sm leading-6">Next: add optional logo and cover photos. Your completed profile will await approval before appearing publicly.</p>}
  </ActionForm>;
}
export function ProductForm({ action, initial = {} }: { action: Action; initial?: { id?: string; name?: string; description?: string | null; price?: number | null; is_active?: boolean } }) {
  const [name, setName] = useState(initial.name || ""); const [description, setDescription] = useState(initial.description || ""); const [price, setPrice] = useState(initial.price?.toString() || ""); const [active, setActive] = useState(initial.is_active ?? true);
  return <ActionForm action={action} label="Save product"><input type="hidden" name="id" value={initial.id || ""} /><label className="block">Product name<input name="name" value={name} onChange={(event) => setName(event.target.value)} required maxLength={160} className={input} /></label><label className="block">Description (optional)<textarea name="description" value={description} onChange={(event) => setDescription(event.target.value)} rows={3} maxLength={3000} className={input} /></label><label className="block">Price in MYR (optional)<input name="price" value={price} onChange={(event) => setPrice(event.target.value)} type="number" step="0.01" min="0" max="9999999999.99" className={input} /></label><label className="flex min-h-12 items-center gap-3"><input name="is_active" type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} className="size-5" />Active product</label><p className="text-sm text-[#5d665f]">Save first, then add an optional image from the products page.</p></ActionForm>;
}
export function ImageForm({ action, kind, productId }: { action: Action; kind: string; productId?: string }) {
  return <ActionForm action={action} label="Upload image"><input type="hidden" name="kind" value={kind} /><input type="hidden" name="product_id" value={productId || ""} /><label className="block">Image file<input type="file" name="file" accept="image/jpeg,image/png,image/webp" required className={`${input} file:mr-3 file:rounded-lg file:border-0 file:bg-rembulan file:px-3 file:py-2`} /></label><p className="text-xs leading-5 text-[#5d665f]">JPEG, PNG or WebP, up to 3 MB. Images are resized and converted to WebP. Uploading replaces the current image, except in the gallery.</p><label className="block">Image description (optional)<input name="alt" maxLength={500} className={input} /></label></ActionForm>;
}
