import Link from "next/link";
import type { Metadata } from "next";
import { PublicShell } from "@/components/discovery/public-shell";
import { REVIEW_TERMS_VERSION } from "@/lib/reviews/terms";
export const metadata: Metadata = { title: "Terms and conditions | Singgah", description: "The rules for using Singgah and sharing community reviews." };
const sections = [
  ["Using Singgah", "Singgah is a local-vendor directory and community review platform. Use it lawfully and respectfully. These terms apply when you use the platform or submit content. If you do not agree, do not submit a review or other content."],
  ["Honest community reviews", "Review only your own experience. Give an honest overall rating; written feedback and product star ratings are optional. Do not impersonate someone, post fake or paid-for ratings, review your own business, or create additional identities to review the same vendor repeatedly. Constructive criticism and negative experiences are welcome when expressed respectfully and truthfully."],
  ["Content that is not allowed", "Do not post threats, harassment, discriminatory abuse, unlawful or defamatory material, spam, advertisements, or content you do not have permission to share. Do not include another person’s private information. Avoid putting phone numbers, email addresses, payment details or other sensitive information in a public review."],
  ["Publication and moderation", "Submitted reviews can become public immediately after validation. Singgah may withhold or remove content that violates these rules or requires investigation. Vendors cannot alter customer ratings or approve or reject their own reviews. Self-service review editing and deletion are not currently available, so check your submission carefully."],
  ["Your content", "You retain ownership of content you submit. You give Singgah non-exclusive permission to store, display and format that content for operating the platform, including displaying reviews and calculating ratings. You confirm that you have the right to submit it."],
  ["Customer identity and review data", "No email signup is required for customer reviews. Singgah creates or reuses an anonymous account and stores a session in your browser to enforce one review per customer per vendor. Your review, rating and date are public; the internal account identifier is not. Singgah stores the accepted terms version and time with new reviews. Security checks use Cloudflare Turnstile, and authentication and review data use Supabase. Do not treat anonymous display as a promise of complete anonymity."],
  ["Vendor accounts and listings", "Keep your account credentials secure and provide accurate business information. Upload only images you have permission to use. New vendor profiles require approval before publication. Listing information, prices and availability may change; customers should confirm details directly with the vendor."],
  ["Purchases and external links", "Singgah does not currently take orders or payments. Purchases and arrangements are made directly with vendors. Reviews represent customer opinions, not endorsements or verified visits. Third-party websites and contact services have their own terms. Nothing in these terms removes rights that cannot lawfully be excluded."],
  ["Service and terms updates", "Features may change or be temporarily unavailable as Singgah develops. Updated terms will be published on this page with a new version date. New review submissions must accept the terms applicable at submission; previous acceptance records are not rewritten."],
];
export default async function TermsPage({ searchParams }: { searchParams: Promise<{ review?: string | string[] }> }) {
  const value = (await searchParams).review;
  const reviewSlug = typeof value === "string" && value.length <= 180 && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value) ? value : null;
  return <PublicShell><main id="main" className="mx-auto max-w-3xl px-5 py-12 sm:px-8"><Link href={reviewSlug ? `/vendor/${reviewSlug}/review` : "/"} className="mb-6 inline-flex min-h-11 items-center text-sm underline underline-offset-4">← {reviewSlug ? "Back to your review" : "Back to Singgah"}</Link><h1 className="font-serif text-4xl">Terms and conditions</h1><p className="mt-4 text-sm text-[#5d665f]">Version {REVIEW_TERMS_VERSION} · Updated 27 September 2026</p><p className="mt-6 leading-7">Help keep Singgah useful, fair and welcoming for local businesses and the people who discover them.</p><div className="mt-6 space-y-8">{sections.map(([heading, text], index) => <section key={heading}><h2 className="text-xl font-semibold">{index + 1}. {heading}</h2><p className="mt-3 leading-7 text-[#46534a]">{text}</p></section>)}</div></main></PublicShell>;
}
